"""Add professional settings

Revision ID: 79ab52c67f04
Revises: a785b50b251c
Create Date: 2026-04-19 11:57:36.200301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ab52c67f04'
down_revision: Union[str, None] = 'a785b50b251c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('import_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'import_mode')
    # ### end Alembic commands ###
