"""Add professional settings

Revision ID: 8c630eb0bcaa
Revises: 95b8049282ca
Create Date: 2026-03-08 11:13:30.568089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c630eb0bcaa'
down_revision: Union[str, None] = '95b8049282ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    op.create_index(op.f('ix_tournee_history_id'), 'tournee_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournee_history_id'), table_name='tournee_history')
    op.create_table('app_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('depot_name', sa.VARCHAR(length=255), server_default=sa.text("'Cabinet Principal'::character varying"), autoincrement=False, nullable=True),
    sa.Column('depot_address', sa.VARCHAR(length=500), server_default=sa.text("'Av. de la Roseraie 72, 1205 Genève'::character varying"), autoincrement=False, nullable=True),
    sa.Column('depot_lat', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('46.1910685'), autoincrement=False, nullable=True),
    sa.Column('depot_lon', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('6.1491002'), autoincrement=False, nullable=True),
    sa.Column('humanity_balance', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('app_settings_pkey'))
    )
    # ### end Alembic commands ###
