"""Recreate settings table

Revision ID: a785b50b251c
Revises: 8c630eb0bcaa
Create Date: 2026-03-08 11:18:08.356337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a785b50b251c'
down_revision: Union[str, None] = '8c630eb0bcaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_name', sa.String(), nullable=True),
    sa.Column('depot_address', sa.String(), nullable=True),
    sa.Column('depot_lat', sa.Float(), nullable=True),
    sa.Column('depot_lon', sa.Float(), nullable=True),
    sa.Column('humanity_balance', sa.Boolean(), nullable=True),
    sa.Column('default_intervention_duration', sa.Integer(), nullable=True),
    sa.Column('enable_safety_margin', sa.Boolean(), nullable=True),
    sa.Column('safety_margin_percent', sa.Integer(), nullable=True),
    sa.Column('enable_break_time', sa.Boolean(), nullable=True),
    sa.Column('break_duration', sa.Integer(), nullable=True),
    sa.Column('max_patients_per_nurse', sa.Integer(), nullable=True),
    sa.Column('max_tour_duration_hours', sa.Integer(), nullable=True),
    sa.Column('theme_preference', sa.String(), nullable=True),
    sa.Column('export_format', sa.String(), nullable=True),
    sa.Column('enable_data_purge', sa.Boolean(), nullable=True),
    sa.Column('purge_after_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
