"""refactor_tournee_model

Revision ID: a81f66cb755d
Revises: 1477f8793bc5
Create Date: 2025-12-31 00:46:41.008204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81f66cb755d'
down_revision: Union[str, None] = '1477f8793bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('tournees_optimise_par_fkey', 'tournees', type_='foreignkey')
    op.create_foreign_key(None, 'tournees', 'users', ['user_id'], ['id'])
    op.drop_column('tournees', 'optimise_par')
    op.drop_column('tournees', 'nb_infirmiers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournees', sa.Column('nb_infirmiers', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tournees', sa.Column('optimise_par', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tournees', type_='foreignkey')
    op.create_foreign_key('tournees_optimise_par_fkey', 'tournees', 'users', ['optimise_par'], ['id'])
    op.drop_column('tournees', 'user_id')
    # ### end Alembic commands ###
