"""gdpr_final

Revision ID: de96dee0d50e
Revises: 
Create Date: 2025-12-30 00:35:53.638558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.security_encryption
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de96dee0d50e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', app.core.security_encryption.EncryptedString(length=500), nullable=False),
    sa.Column('prenom', app.core.security_encryption.EncryptedString(length=500), nullable=False),
    sa.Column('adresse', app.core.security_encryption.EncryptedString(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('telephone', app.core.security_encryption.EncryptedString(length=255), nullable=True),
    sa.Column('email', app.core.security_encryption.EncryptedString(length=500), nullable=True),
    sa.Column('heure_preferee', sa.String(length=20), nullable=True),
    sa.Column('test_a_jeun', sa.Boolean(), nullable=True),
    sa.Column('retour_rapide_labo', sa.Boolean(), nullable=True),
    sa.Column('preference_notification', sa.String(length=20), nullable=True),
    sa.Column('notes', app.core.security_encryption.EncryptedString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_table('notifications_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('erreur', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_log_id'), 'notifications_log', ['id'], unique=False)
    op.create_table('tournees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('nb_infirmiers', sa.Integer(), nullable=False),
    sa.Column('duree_totale_min', sa.Integer(), nullable=True),
    sa.Column('distance_totale_m', sa.Integer(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('optimise_par', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['optimise_par'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournees_id'), 'tournees', ['id'], unique=False)
    op.create_table('tournees_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournee_id', sa.Integer(), nullable=True),
    sa.Column('infirmier_num', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.Column('heure_arrivee_estimee', sa.Time(), nullable=True),
    sa.Column('heure_depart_estimee', sa.Time(), nullable=True),
    sa.Column('heure_arrivee_reelle', sa.Time(), nullable=True),
    sa.Column('heure_depart_reelle', sa.Time(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gmaps_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tournee_id'], ['tournees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournees_details_id'), 'tournees_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournees_details_id'), table_name='tournees_details')
    op.drop_table('tournees_details')
    op.drop_index(op.f('ix_tournees_id'), table_name='tournees')
    op.drop_table('tournees')
    op.drop_index(op.f('ix_notifications_log_id'), table_name='notifications_log')
    op.drop_table('notifications_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
